### ISSUE TITLE
curved gaussian

### ISSUE THREAD

**Issue by zji90** [linnykos/esvd#2]
Hi Kevin,
I wonder if I run eSVD using family=curved_gaussian, should I use data on the original scale (data without log-2 transformation), or the log2-transformed data? Thanks!

**Comment by linnykos** [comment]
Personally, I would suggest using it on the data without the log-2 transformation. That is what we argue for in our eSVD paper.

Of course, from a purely algorithmic point of view (i.e., outside the scope of a genomics-specific application), either one could be done as long as all the entries in your matrix (with or without the log-2 transformation) are positive.
