### ISSUE TITLE
Optimal number of k

### ISSUE THREAD

**Issue by zji90** [linnykos/esvd#3]
It seems that eSVD needs to be rerun with different choices of k. I wonder whether it is possible to select or heuristically determine the optimal number of k for any dataset. Thanks!

**Comment by linnykos** [comment]
Personally, in our eSVD paper, we suggest using a matrix-completion approach to tune for the missing values. This can be currently best exemplified when you look at the code I use to do the analysis in the eSVD paper.

Specifically: 

1. In https://github.com/linnykos/esvd/blob/revision/main/step1_naive_svd.R (lines 10-13), we construct `missing_idx_list`, a list of entries to purposefully set as NA.
2. In https://github.com/linnykos/esvd/blob/revision/main/step3_scalar_tuning.R (lines 5-35), we fit many eSVDs, one time per (different set of missing values) x (different value of tuning parameters you want to select from, including the possibly different values of `k`). Observe in lines 18-19, we are purposefully setting entries in `dat_impute` according to the lists in `missing_idx_list` to become `dat_impute_NA`. In essence, we are fitting the embedding using the non-missing entries (the "training set").
3. In https://github.com/linnykos/esvd/blob/revision/main/step4_factorization.R (lines 5-17), we then ask "Given estimated fit based on the non-missing entries, how well did we estimate the values at the missing entries (i.e., the "testing set")?" This is done using `eSVD::tuning_select_scalar` function. There are many ways one could hypothetically answer this question, but the function we developed chooses `k` here based on the principal angle -- how close the principal component on the [expected predicted value based on the fit] x [purposefully omitted value] scatterplot is.

Hope this helps!
